language: cpp


before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libXxf86vm-dev libXi-dev
 - sudo apt-get install qt5-default qttools5-dev-tools

script:
  - qmake SLProjectCommon.pro
  - make

os:
  - linux
