language: cpp

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y qt5-qmake; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install; fi

before_script:
  - qmake

os:
  - linux
  - osx
