language: cpp
sudo: required

services:
    - docker
    
before_install:
 - docker run -d --name ubuntu -v $(pwd):/travis ubuntu:latest tail -f /dev/null
 - docker ps

install:
 - docker exec -t ubuntu bash -c "apt-get update;
   apt-get install git;
   apt-get install qtcreator qtbase5-dev qt5-default;
   apt-get install libxxf86vm-dev libxcursor-dev libxrandr-dev libxi-dev libxinerama-dev libudev-dev;
   apt-get install libavcodec-dev libavformat-dev libswscale-dev;
   apt-get install g++;
   apt-get install libdc1394-22"
 
script:
 - docker exec -t ubuntu bash -c "cd /travis;
   qmake -recursive;
   make"

branches:
  only:
    - master
    - develop
    
notifications:
    email:
        recipients:
          - marcus.hudritsch@bfh.ch
        on_success: never
        on_failure: always