language: cpp


before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install libXxf86vm-dev libXi-dev libudev-dev
 - sudo apt-get install qt5-default qttools5-dev-tools

script:
#  - cd lib-SLExternal
  - qmake
  - make
#  - cd ..
#  - cd lib-SLProject
#  - qmake
#  - make

os:
  - linux
