version: 1.0.{build}
os:
- Visual Studio 2013
- Visual Studio 2015
configuration:
- Debug
- Release
platform: x64
build:
  project: SLProject_no_Qt.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - marcus.hudritsch@bfh.ch
  subject: SLProjekt Build Error on AppVeyor
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false